name: jodo_app
description: A new Flutter project for ISL communication.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Plugins
  supabase_flutter: ^2.0.0
  google_sign_in: ^6.1.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6
  video_player: ^2.9.5
  chewie: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true